# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 16:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 7, 26, 0, 8, 3, 286042))),
                ('update_time', models.DateTimeField(default=datetime.datetime(2018, 7, 26, 0, 8, 3, 286042))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='User.Base')),
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('avatar', models.CharField(max_length=300, null=True)),
                ('self_introduction', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_tb',
            },
            bases=('User.base',),
        ),
    ]
