# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 07:58
from __future__ import unicode_literals

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('ticket', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('avatar', models.ImageField(blank=True, max_length=300, null=True, upload_to='user_avatar')),
                ('self_introduction', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_tb',
            },
            bases=(User.models.BaseMode, models.Model),
        ),
    ]
